(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.元件6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#70530B").ss(1,1,1).p("A3+hBUAOhAD3AgUgDbQAhgEAhgDIAGgB");
	this.shape.setTransform(538.7,83.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AYDjbIAAAAA4CDcIABAAQABAAABAA");
	this.shape_1.setTransform(223.9,64.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#624600").ss(1,1,1).p("EA3BgHyIA7ANQBCATAZAZQAhAhAaA8QAdBDAAA8QAABzhYBXQgiAigwAYQglATg4ARQh6AmiAgCQgMgDgLgCAiqnaQeIFhRlkuQA6gPA3gRQADgBADgBQAGgCAIAAAimoeQcuF7S7kZQBGgQBDgSQADgDADgDEgy5gAgQAfgBAfgBUAn4gBlAHHgFREgz2gBHQADAAADAAEgzOgAdQAGgCAGAAEgzVgBIQAtgBAtgCUAp/gBeAE5gF0Egx0ACzIAEAEIgBAxQgFAUgFAVQgBACgBADQgDALgDAMQgIAYgNAcQgMAbgLASQgJAOgIAJQgrAqggAVQhFAthZAJQhcAKhOgLQgYgEgUgFQgdgHgSgOEgxeAErUAnXgCHAIVgEl");
	this.shape_2.setTransform(396.7,89.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#916511").s().p("EgveAGCIAAAAIgDgGIgBgBQAHgcACgdQADgfgCgfIgBgFQAFgHAAgJIAAgGQgBgKgFgOQgOgmgRgcIgCgEQgNgTgaghIgQgSIgGgFIABgCIAAgFIgBgCIgBAAIA+gCUAn3gBkAHIgFRIAAAAIABAAIACADIADgBIADgBIAFAAQAAABAAAAQABAAAAAAQABAAAAgBQABAAAAgBIABgCQeIFhRlkuQA5gPA4gRIAGgCIgFAHQgPAXgUArIAAAAIgHAQIAAAAQgCAFADAFIAGAHQAIAIACAJIgKARQgTAlgDAqQgBATADAnIAAACIABAGQADAXAFAKIAFANIAAAGIABABIgBAAIgDADIAAACIhGAMUggVADbgOhgD3UgIUAEmgnXACHIAAgBg");
	this.shape_3.setTransform(383.9,81.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AD910E").s().p("AgHFCQgjgBgQgGQgZgJgZgZQgrgtgNg8QgEgSgCgXQgKhUgChTIADgCQABgCgDgDIgBgBQgDh3ALh5QABAAAAABQAAAAABABQAAAAABAAQABAAAAAAIABAAIAAgDQAAgEAFgHIAEgGQAEgDADABIABAAQALgLAbgEQBygQBPAZQAeAKANAQQAKANAFAcIAGAmQAFAjAGA1IASCnIAAABIAIBNIADAxQABAYgDAPQgFAcgVAXQgMANgPAKQgKAGgLAEQgoAShDAAIgHAAgAgdA5IgLAEQgNAHgKAQQgIALgEAKIgDALIgCAMQgCASAAAXIACAOIAEAJQATAkATAKIANAHIAKAJQAFADAFABQAHADARAAIAWAAIAKAAQAHgBAJgHQAYgPAJgRIAHgQQAFgOAAgIIABgNIADgKIACgMQABgXgEgNQgFgTgNgMQgGgEgOgHQgQgHgGgCQgMgDgVAAIgpgBIgFAAIgFAAg");
	this.shape_4.setTransform(44.3,80.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D9B84D").s().p("Egw1AD/IgGgFIgFgEIgTgUIgBgBIgCgBIAAgBIAEgDIACABIAEgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgBIBagDUAqAgBfAE5gFzIADABIAEABIAOABIAEABQADAAABgEQcuF6S7kZQBFgQBEgSQgKAKgIALIgHACQg3ARg5AQQxlEs+IlfIAAgCIgBgFQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBAAAAAAIgGAAIgBAAIgDACIgDACIAAABIAAACIAAACIAAAAUgHIAFQgn4ABlIg9ADIgDgBIAAAAIgCAAIgBABIgCAAg");
	this.shape_5.setTransform(382.7,61.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E5DC60").s().p("AgiBbIAAAAIgGgIIgCgCIAAgBIgBgBIAAAAIgCgBIAAAAIgCgBIAAgCIgEgFIgBgBIAAAAIgBgEIgFgFQgCgDAAgCIgCgBIgBAAIAAgBIABgBQANgfAJgQQANgYAPgTQAPgWAUgNIAYgPIALgHIAGA2IgCgDQg7A8ggBNIgCADIgDgFg");
	this.shape_6.setTransform(699.6,47.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#917123").s().p("Eg16AGXQgmgCghgIQghgJgcgPIgCgCQhBglgYg9QgYg/AYhYQAZhhA8gbIACANQACAZAEATQAIAnATAiQAPAZASATIAQAPQASAQAVAHQARAGAeABQA/ACAlgKQAcgIAUgNQA3gOAVgnQAJgSACgZQACgQgCgdIAAgPQATAeAKAkQAMAogDAoQgCApgRAmQgQAngdAdQgaAcgjASQgWAMgbAJQgzAQg4AAIgYgBgEA1AgBMQgegEgYgKQgMgGgKgGQgLgHgJgJQgRgPgOgXQgegwgDgsQgCgaAHgXQAIgZAQgSIAKAJIABABIAAAAQAJAIAKAFQATAJAeAEQBUALBPgYQAfgIAUgNQAXgFATgUQAQgSAKgaIABACQAoA0AOAvQASA+gVAyQgRAqg2AqQgUAPgQAHQgVAJgwADQghADgZAAQgcAAgUgDg");
	this.shape_7.setTransform(384.8,92.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#C4AC40").s().p("Eg3wAIDQgZgEgUgFQgVgIgZgNIgMgGQg8ghgjgnQgKgLgOgUIgXgkQgSgegIgTQgJgWgEgbQgJg3AMg6QAMg4AdgyQA4heBsg8QAPgJALgCQACBDAHBDIgCAAQhCAcgbBoQgaBoAiBGQAXAvAwAfIAVAMQAcAOAhAJQAeAIAjACQA+AFA4gNIAYgGQAlgMAegTIAQgLQAmgdAZgqQAIgNAHgPQANgdAFggQAHgwgLgvQgLgwgcgoQgDgDgCgBIgDhBIAUASIADADIAMANIAKANIAGAJQAiA6AaBEIABABQABADAAACIAFAKIAAAAIABAGIABAFIACgBIgBAxIgKApIgBAFIgHAXQgIAZgMAbQgNAbgKASQgKAPgIAIQgqAqghAVQhFAthYAJQgrAFgoAAQguAAgpgGgEA0QABZIgXgFQgXgGgWgJQg+gZgtgsIgTgTQgcgggbgxQgmhEgHg2IgCgPIABgZQADgjAOgdIAIgOIAFgGIABgCIAEADIAEAHIAFAHIADADIACgCIADgCIABgBIAAAAIAAAAIADgCIgBgCIADgIQAYhBAzgzQAJgKABgHIAFAbQAJA0ALAbQAIASALANIgCAAQgEABgFAGQgbAnAEA0QACArAcAvQAPAaAPAOQAMANAQAKQALAHANAFQAWAKAcAFQAsAIBIgFQAngDAUgHQAbgKAfgZQBFg5AJg+QADgZgGgfQgFgVgMghQgLgagIgPQgMgWgPgNIgEgCIAAgCQAHgYAEgoIADgqIA8ANQBCATAZAZQAhAhAaA8QAcBDAAA8QAABzhXBXQgjAjgvAXQgmATg3ARQh1Akh7AAIgLAAg");
	this.shape_8.setTransform(386.8,92);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231808").s().p("Eg1dAE2IgCAAIAEgGIAHgLIACABQAFAEACADIAFAHIAAAAQgEADgLAAIgIgBgEg1sAErIgBgIIABgKIACgEIAAABQAAACAEACIAKAGIAAAAIgMARQgDgDgBgDgEg1OAEdIAIgJIACgEQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQgEAAgDAEIgHAIIgHgEQgEgDgDAAIgCABIACgDQADgEADgBQAEgDALAAQAGAAADADIAIAKQACACAAAHIgBANIgBACQgGgHgJgHgEA1NgDtQgPgDgJgNQgHgLgBgQQgBgSAKgIQAIgFARABIAPABQAEAAADABQADACACAGQAEAJAAAKQABAKgEALIgGgJIgNgMIgDgDQAEgHAEgEQAFgEAAgDQgBgDgGgBQgGADgFAHIgDAGQgHgFgFgCQgIgDgBAFQgBAEAHAEIAKAGIgMAZQgDAFACADQAAABABAAQAAABABAAQABAAAAAAQABAAABAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABgBQACgCACgGQACgHAGgMIAGAFQAIAHADAGQADAHADABIAAAAIgBABQgHALgNAAIgFAAg");
	this.shape_9.setTransform(387.2,68.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#D9CE37").s().p("Eg1rAF+QgWgHgSgQQgRgQgJgWQgIgWABgXQACgYAMgUQAIgPAMgIQAOgIAhABQAnACASAHQAgALAJAbQAEAOgDAZQgDAbgEAPQgHAXgOANQgPAPgWAEIgPABQgOAAgNgEgEg2FADZQgDACgFAFIgOAMQgPAPgDAYQgDAWAJAVQAIATANANQAJAJAPAKQAKAGAGABIAOACIAbgBQAXgDAPgdIAJgXQAFgSABgaQAAgPgCgIQgCgFgGgJQgHgKgHgFQgJgFgNgCQgXgEgoAAQgIAAgEACgEA0NgCqIgRgQIgBgBIgPgKQgFgEgFgIIgIgOIgKgOQgCgGAAgLQAAgTADgTQACgNAEgLQAMgdAXgRQAFgEAGgCIAJgDIAKgHQANgJAeACQAgACAQAIQAMAFANAOIAaAiQAGAKACAEIAGAVQACAKgCAOIgFAYIgEAMIgIATQgIARgIAIIgQAMIgNALQgMAHgXABIgFAAQgsAAgVgSgEA0agFpQgRAIgOAMIgJAJQgQAPgFAOQgFAMgCAUQgBAIAAAHQACAIAJAOQATAdAVARQAJAIAKAGQATALAWACQAWACATgJQAYgLAOgcQALgWAEggQABgNgBgHQgCgMgFgNQgEgKgGgLQgMgTgVgLQgUgLgXgBIgEAAQgWAAgRAIg");
	this.shape_10.setTransform(387.8,67.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#935D0B").s().p("Eg1gAFrQgEgBgGgEIgOgIIgKgIQgagbgBgcQgBgLADgJQACgIADgEIAFgIIACgFIAGgGIAHgFIAJgHIAGgBQAdgCAdAFQAQADAIAFQAFADAEAIQAHAMABAKQABALgDAQQgDAVgCAFIgJATQgGAKgFAFQgGAGgJACIgNABIgPAAIgEABIgGgBgEg1nAEHQgJAHgEAKQgFALACALIADAIQACAEAEADIACABQAAABAAAAQABABAAAAQAAAAABABQABAAAAAAIABAAQALAHAOgBQAKgBAGgEQANgKgBgVQAAgNgFgJQgJgLgNgBIgEgBQgLAAgKAHgEA1IgCvQgbgEgZgVQgTgQgTgcQgGgJgCgHIAAgPQACgQADgHQAFgNAMgNIAPgOQAlgdAmAFQALACAHAEQAGACALAIIAPANQAFAGAEAHQANAZAAAWQAAAQgJAcIgHARIgHAKIgJAKQgKAKgPAFQgJACgKAAIgKAAgEA1HgE9QgWADgHAJQgHAIAAARQAAAYAJAOQAMASAXACQAIACAJgDQANgFAHgQQAEgLABgSIAAgFQgBgagNgJQgGgEgLgBIgDAAIgQABg");
	this.shape_11.setTransform(387.2,67.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#805E1D").s().p("Eg4ZALQIgPgBQgcgBgZgEQgfgFgbgJIgNgFQAUAFAZAEQBOALBcgKQBYgJBFgtQAhgVAqgqQAJgJAJgOQALgSAMgbQAMgbAIgZIAHgXIABgFIAKgpIABgxIABgBQADABAGgDIACgCQAFAZgCAeQgDAagIAdIAAACIgCAHIgBADIgMAhQgOAjgSAeQgaApgjAdQg2AvhPAVQgwAOg1ACIgfABIgTAAgEg0+AFcQAOgUAGgcQACgMABgNQACgZgEgpIgCgPIgHg+IAAgBIgcj/QgEgigGgTQgGgSgJgNQgGgHgGgFQgMgKgVgHQgngOg0gCQgggBg9ADQgVABgMADQgRAFgKALIgGAIIAAgBQADgXArgIQBngTBNAMQAsAIAYARQAJAHAHAIQAOAQAKAXQAKAaAIApIAHA0QAIA9AEBiIACAiIAAAIIAAAEIAAABIAFBtQABAbgDANQgEAagTAVQgMANgOAIIAJgLgEgybAEzIgFgLIgJgVIgqhVIgIgKQgLgOgOgOIgQgQIgEgDQgEgEgDgBIgBAAIgBgVIACACIAdAcIAcAcQAhAjAVAnQAQAdAKAgQAEAJAAAIQgBAFgCAEIgCAAQgEACAAAEIgHAFQgCgOgHgQgEAzCAEdQgdgBgcgGQCBACB6gmQA3gRAmgTQAvgYAjgjQBXhXAAhyQAAg8gchDQgag8ghghQgZgZhCgTIg8gNIACgcIADAAIADABQAvgIAyAZQArAWAkArQApAyAVA9QAWA/gEA/QgEBAgdA6QgeA7gyAnQgtAjhKAbQh2ArhmAAIgegBgEA1ygDRQANgmAEgjQAEgfAAg9IAAiXQAAgygEgYQgFghgPgfQgLgXgNgHQgLgHgWgCIgOgBIgBAAQgogCg1AEIgFAAQhMAIgmADIghACIgZADIgVAGQAEgHALgEQAKgFAQgDIADAAQCXgVBTAAQAvAAAVAQQAPALANAcQAQAmAHAxQAFAjABA2QABBhgJBgQgEA1gNAdQgMAcgTAQQALgQAIgYg");
	this.shape_12.setTransform(400.3,73.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#A17E09").s().p("Ag9EdQgugEgXgTQgVgRgOgqQgNgmgHgxIAAgFIAAAAIgHg8IADgCQAAgEgDAAIgCgSIgFhZQgBg0AKhrIADghQAXgNAlgCQAVgCArAAQAWgCApgIIAWgDQAjgDA6ABQAbABAMAHQAOAHALAYQANAbAFAcQADAXAAAtIAACtIgBA0QgEA4gVAzQgMAcgPAMQgKAIgVAIQhDAXhFAAQgUAAgVgCgAgoC+QARAJAHADQAMAEAaACQAfABAOgHQAIgEAMgKIAUgUQAPgRAHgUIAIgeQAEgQABgLQAAgKgCgIIgHgSIgCgDQgagzgjgSQgdgOgxADIgPACIgPAHQgWAMgJAJIgMANIgLAPIgHARIgEAMQgDAKgCANQgBANAAANQAAASADAJQADAGAFAGIARAZQALAQALgCQAAAEADAEQADADAEgBQAAAGAJAFg");
	this.shape_13.setTransform(725.6,32.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#624600").s().p("Eg2rALaQgfgCgbgEIgYgEQgbgGgYgJQgcgLgugcQgvgcgTgTQgSgSgTgbIgFgJQgdgpgOggQgWgwgBgrQgBgXAKg2QAGgfAGgYQAkh0CUhjQAagRASgBQgCh+AMh+QADABACAAQABgWANgNQAKgJAUgFQA8gQBdAEQApADAaAGQAkAJAXAVIAIAIQAbAfAOA/QAIAqAFA1IAGBgIACAiIADgBIAGAAIAFABIAEAAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABIABADIAAABQAAABAAAAQAAABAAABQgBAAAAAAQAAABgBAAIgEABIgCAAIgFADIABAAIABABIACABIATAUIAFAEIAGAFIABABIABgBIAAgBIADAAIAAAAIADABIAAAAIABACIABAFIgBACIAFAFIAQARQAbAhAMAUIACADQASAdANAmQAFANACALIAAAFQAAAKgFAHIAAAEQADAggDAeQgCAegIAcIACABIACAFIAAABIAAABIgBADIgFAAIgBAAQgIAdgOAcIgJASIgMAUQgWAkgfAdIgNAMQgiAegoATQgmATgtAKQgzALg7AAIgjgBgEg5JAA5QhsA8g4BfQgdAzgMA3QgMA6AJA3QAEAcAJAVQAIAUASAeIAXAjQAPAVAJALQAjAnA8AgIAMAHQAZANAVAIIANAEQAbAKAfAFQAZADAcACIAPAAQAaABAYgBQA2gDAvgNQBPgVA2gvQAjgeAagpQASgdAOgkIAMggIABgEIACgHIAAgBQAJgeACgaQACgegFgZIgCACQgGADgDAAIgBAAIgDgDIADADIgCABIgBgEIgBgGIAAAAIgFgLQAAgCgBgDIgBgBQgahDgig7IgGgKIgKgNIgMgNIgDgCIgUgSIADBBQADABACAEQAcAnALAwQALAwgHAvQgFAggNAeQgGAOgJAOQgZAqgmAdIgPAKQgfAUglALIgYAHQg4ANg+gFQgjgDgegIQghgIgcgPIgVgMQgwgegXgwQgihGAahoQAbhnBCgdIACgBQgGhDgChCQgLACgQAIgEg4qAK4QgcgHgSgOQASAOAcAHgEg56AE8QgYBYAYA/QAXA+BBAkIADACQAcAPAhAJQAhAIAmACQBFAEA9gTQAbgJAXgMQAjgSAagcQAcgdARgnQAQgmADgpQACgogLgoQgKgkgUgeIABAPQABAdgBAQQgCAZgKASQgUAng4AOQgUANgbAIQgmAKg+gCQgfgBgQgGQgVgHgSgQIgQgPQgTgTgOgZQgUgigHgnQgEgTgDgZIgBgNQg8AbgZBhgEg4kAAmIABABQADACgCADIgCABQACBVAJBTQADAYAEASQANA7AqAtQAaAaAYAJQARAFAjABQBIABAqgSQALgFAKgGQAQgKALgNQAVgXAGgcQADgOgBgYIgDgxIgIhOIAAAAIgTinQgFg1gFgkIgHglQgFgcgKgOQgNgQgegJQhPgZhyAQQgbAEgMAKIAAAAQgDgBgEADIgEAGQgFAHgBAEIAAAEIAAAAQgBAAAAAAQgBgBgBAAQAAAAAAgBQgBAAAAgBQgLB5ADB3gEg11gD8QA0ACAnANQAVAHAMAKQAGAGAGAHQAKAMAFASQAGAUAEAhIAcEAIAAAAIAHA/IACAPQAEAogCAZQgBAOgCAMQgGAbgOAVIgJALQAPgIALgNQATgVAEgbQADgNgBgbIgFhsIAAgBIAAgFIAAgHIgCgiIAHAAIgHAAQgEhjgIg8IgHg0QgIgqgKgZQgKgYgOgPQgHgJgJgGQgYgSgsgHQhNgMhnATQgrAHgDAYIAAAAIAGgHQAKgLARgFQAMgDAVgBQArgDAcAAIAWABgEgyWACBIABAAQADAAAEAEIAEAEIAQAPQAOAOALAOIAIALIAqBUIAJAVIAFALQAHAQACAOIAHgEQABgFADgBIACAAQACgEABgGQAAgHgEgJQgKgggQgdQgVgoghgiIgcgdIALgCIACAAIgCAAIgLACIgdgcIgCgCgEg1bAFTQgQAAgIgCQgGgCgEgDIgKgIIgOgHQgSgKgTgkIgFgJIgCgPQAAgWACgSIACgNIADgKQAFgLAHgLQALgQAMgGIALgFIALAAIApABQAVAAAMAEQAHABAQAHQAOAHAGAFQANALAFAUQADANgBAXIgBAMIgEAJIAAAOQgBAHgFAOIgHARQgIAQgYAQQgJAGgHABIgKABgEg2WACZQgLAHgJAPQgLAUgCAYQgCAYAJAVQAIAWASAQQARARAWAGQAVAHAVgEQAXgEAOgOQAOgNAHgXQAFgQADgbQADgZgFgOQgJgagfgMQgTgGgmgCIgHAAQgcAAgNAHgEg1uAFAQgFgBgKgGQgQgKgJgJQgNgNgIgUQgIgUACgWQAEgYAPgPIANgNQAFgFAEgBQADgCAJAAQAnAAAYAEQAMABAJAFQAIAFAHALQAGAJABAFQADAHAAAPQgBAagFATIgJAWQgQAegWADIgcAAIgOgBgEg19ACqIgGABIgJAHIgHAFIgGAGIgCAFIgEAIQgDAEgDAIQgDAJABALQACAcAaAbIAJAIIAPAIQAGAEAEABQAEABAFgBIAQAAIAMgBQAKgCAFgGQAGgFAFgKIAJgTQACgFAEgVQACgQgBgLQAAgKgHgMQgFgIgFgDQgIgFgQgDQgUgEgVAAIgRABgEA08AEmIgBAAQgggCgfgGQg9gLgsgaQghgTgigjIgQgRIgDgEIgBAAQgxg3gag2IgEAAIgFgCQgEgCACgDIgFgBIAAAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgCIADgDIAAAAIAAgBIgBgHIgFgMQgFgLgDgVIAAgGIgBgDQgDgmABgTQAEgqATglIAKgRQgDgJgHgIIgHgIQgCgFACgEIgBgBIAHgPIABAAQAUgrAPgYIAFgGQAIgMAJgKIAGgFQAagbAhgQIABAAQgFg3gBg3IAAgGQgBhHAHgyIAEggQABgNgBgIQgCgPAEgFIADgDQAAgDAEgGIAHgGQAHgHAKgFIAQgGIAPgEIAjgFIBwgMQAzgFAoACIAUABQAkAEASANQAQAMANAeQARAnAHApQAFAhABAwQACBEgDBEIABAAIAAgBIACAAIAAAAIABABIAAAAIAEAAIAIgBQAuAAAuAZQAqAWAiAnQArAxAXA+QAYA/gCBAQgCBBgcA8QgdA9gxAqQgoAig+AbQhUAlhWANQgnAFgnAAIgjgBgEAv6gCdIgFAHIgIAOQgOAdgDAiIgBAZIACAPQAHA2AmBDQAbAxAcAhIATAUQAtArA+AZQAWAJAXAGIAXAGQAcAFAdACQBzAHCHgyQBKgbAtgjQAygnAeg7QAdg6AEhAQAEg/gWg+QgVg+gpgyQgkgqgrgWQgygagvAJIgDgCIgDABIgCAbIgDArQgEAogHAYIAAABIAEADQAPANAMAWQAIAPALAaQAMAgAFAWQAGAegDAZQgJA9hFA5QgfAagbAJQgUAHgnADQhIAGgsgIQgbgFgXgKQgMgGgLgGQgQgKgNgNQgPgPgPgZQgcgugCgsQgEg0AbgnQAFgGAEAAIACAAQgLgOgIgSQgLgagJg0IgEgbQgBAHgKAJQgyA0gZBBIgDAIIABABIgCACIgBAAIAAAAIgBABIgDADIgCABIgDgDIgFgHIgEgHIgEgDIgBACgEAyEgBnQgIAXACAaQAEAsAeAvQAOAXAQAPQAKAJAKAHQALAHAMAFQAYAKAdAEQAmAFBEgFQAwgDAWgJQAPgHAUgPQA2gqASgpQAUgygRg+QgPgvgng0IgBgCQgKAagRASQgSAUgYAFQgTANgfAIQhPAYhUgLQgfgEgTgJQgKgFgIgIIgBAAIgBgBIgJgJQgRASgHAZgEA1EgKyIgVACQgrAIgVACQgrABgVABQgmACgWAOIgDAhQgKBqABA0IAFBbIABASQAEAAAAADIgDADIAGA7IAAABIABAEQAHAyAMAlQAPAqAVARQAXATAuAFQBbAJBXgfQAVgHAKgJQAOgMAMgcQAVgzAFg3IABg1IAAitQAAgugEgWQgEgcgNgbQgMgYgOgIQgLgGgcgBIgWAAQgqAAgdACgEAxZgFVIgYAPQgTANgQAWQgQATgNAZQgIAQgOAfIAAABIAAABIAAAAIACABQAAACACADIAGAFIABAEIAAAAIAAABIAEAFIABACIACABIAAAAIACABIAAAAIAAABIABABIACACIAFAIIAAAAIAEAFIABgDQAihNA7g9IACADIgHg2IgLAHgEA2igK/IAOABQAWACALAHQANAIALAWQAPAgAFAgQAEAZAAAyIAACXQAAA9gEAeQgEAkgNAlQgIAYgLAQQAUgPALgcQANgdAEg1QAJhggBhhQgBg2gFgkQgHgxgQglQgNgcgPgLQgVgRgvAAQhSAAiYAWIgDAAQgQACgKAFQgLAFgEAGIAVgFIAZgDIAhgDQAmgCBMgIIAFgBQA1gEAoACIABAAIAAAAgEAwQgEhQAGgCAIAAQgIAAgGACgEg1xAENIgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAgBAAIgBgCQgFgDgCgEIgCgIQgCgLAEgLQAFgKAIgHQAMgIANACQAOABAIALQAGAJAAANQABAVgOAKQgGAEgJABIgDAAQgMAAgKgFgEg1kAEAIgDAGIABAAIAIABQALAAAEgDIAAAAIgFgHQgCgDgFgEIgCgBIgHALgEg11ADpIgBAKIABAIQABADADADIAMgRIAAAAIgKgGQgEgCAAgCIAAgBIgCAEgEg1OADdQABAAAAABQAAAAAAAAQABABAAAAQAAABgBAAIgCAEIgIAJQAJAHAGAHIABgCIABgNQAAgHgCgCIgIgKQgDgDgGAAQgLAAgEADQgDABgDAEIgCADIACgBQADAAAEADIAHAEIAHgIQADgEAEAAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABgEA1EgDGQgagCgMgEQgHgCgRgJQgKgGABgFQgEAAgDgDQgEgDABgEQgLACgLgRIgSgYQgFgHgCgGQgEgIAAgSQAAgNACgNQABgOAEgKIAEgMIAHgQIAKgRIAMgNQAKgJAWgMIAOgHIAPgCQAzgDAcAPQAkARAaA0IACAEIAGARQACAIAAAKQAAALgFARIgIAdQgGAUgPASIgVATQgLALgJAEQgLAFgaAAIgIAAgEA0VgGzIgKAHIgKADQgGADgEADQgYARgLAdQgEALgDAOQgDATAAATQAAAKADAGIAJAPIAJANQAFAIAFAFIAOAKIACABIARAPQAWATAvgBQAYgBALgHIAOgLIAPgMQAIgIAJgRIAIgSIADgNIAFgYQADgNgDgKIgGgVQgBgFgHgKIgaghQgNgOgMgGQgQgHgfgCIgLgBQgWAAgKAHgEA1AgDZQgVgCgTgLQgKgGgJgIQgVgSgUgcQgJgOgBgJQgBgGACgJQACgUAEgLQAGgOAPgQIAKgIQAOgNAQgHQAUgKAYABQAWABAVALQAUAMAMATQAHAKADALQAGANABAMQABAGgBANQgDAhgLAVQgOAcgZAMQgPAHgRAAIgJAAgEA0CgGHIgQAOQgMANgEANQgDAHgCAQIgBAPQACAHAGAJQATAcATAQQAZAVAcAEQAOACAPgEQAPgFAKgKIAIgKIAIgKIAHgRQAJgcAAgQQAAgWgOgZQgDgHgGgGIgOgNQgLgIgGgCQgHgEgMgCIgLAAQggAAgfAYgEA1FgETQgWgCgMgSQgJgOAAgYQAAgRAHgIQAHgJAWgDQAMgBAHAAQAKABAHAEQAMAJABAaIAAAFQgBASgEALQgHAQgNAFQgFACgGAAIgGgBgEA0tgFiQgKAIABASQABAQAHALQAJANAPADQAQACAJgNIABgBIAAAAQgDgBgDgHQgDgGgIgHIgFgFQgGAMgDAHQgCAGgCACQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQgCgDADgFIANgZIgLgGQgHgEABgEQABgFAIADQAFACAHAFIADgGQAFgHAGgDQAGABABADQAAADgFAEQgDAEgFAHIADADIANAMIAGAJQAEgLAAgKQgBgKgEgJQgCgGgDgCQgDgBgEAAIgPgBIgFAAQgNAAgHAEgAhmkwIAAAAIAAgBIAAgCIAAgCIAAAAIADgDIADgCIABAAIAFAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAIABAFIAAACIgBACQgBABAAAAQgBAAAAABQAAAAgBAAQAAAAgBgBIgEAAIgDABIgEAAgAhZlzIgNgBIgFgBIgCgBIgCgCQgBgCACgDIAGgCIAOABQAGABACABQACADAAADIAAAAQgBAEgDAAIgBAAIgEgBg");
	this.shape_14.setTransform(388.1,73.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.元件6, new cjs.Rectangle(0,0,776.2,146.2), null);


(lib.元件5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 18
	this.instance = new lib.元件6();
	this.instance.parent = this;
	this.instance.setTransform(388.1,73,1,1,0,0,0,388.1,73);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.元件5, new cjs.Rectangle(0,0,776.2,146.2), null);


// stage content:
(lib.天平 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.instance = new lib.元件5();
	this.instance.parent = this;
	this.instance.setTransform(628.8,625.2,1,1,3.5,0,0,388.3,73);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1036.8,1128.8,783.6,193);
// library properties:
lib.properties = {
	width: 1600,
	height: 1200,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;